
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
